export {
  staticKeys,
  useColorsQuery,
  useTitlesQuery,
  useCurrenciesQuery,
  useOutfitsQuery,
  useSpecializationsQuery,
  useTraitsQuery,
  useBackstoryQuestionsQuery,
  useBackstoryAnswersQuery,
  useMaterialCategoriesQuery,
  useHomeNodesQuery,
  useHomeCatsQuery,
  useHomesteadGlyphsQuery,
  useItemsQuery,
  useSkinsQuery,
} from "./queries"
